### PR TITLE
Add themes

### PR DESCRIPTION
**Pull request by bashbunni**
## Changes made:
- [x] Created a `Theme` struct for new themes and used Catppuccin themes as a starting point. 

## Supported themes:
- Catppuccin "mocha", "macchiatto", and "latte" (light theme)
- Default (anything other than those values

One thing I noticed and haven't been able to debug is that the first time I run `gocovsh` it gives a nil pointer reference, but the second time I run it, there's no problem. Attached a GIF for your reference which includes a demo of both the error and the working style for latte theme. 

gocovsh-themes

#4

### CODE REVIEW

**Comment by orlangure** [comment]
Hi @bashbunni, thank you for working on this, and for adding Catppuccin to the project (I wanted to try it for a while).

Regarding the nil pointer, I'm unable to reproduce it, and from the stack trace it seems that the problem is somewhere deeper in the bubbles list or some other related library.  Have you noticed anything like that with previous versions?

Regarding the code and the feature, I like it! I would love to take it further in the future, and allow to provide configuration files in addition to environment variables. This change wouldn't be breaking because you already used `GOCOVSH_` prefix. We'll allow using a `theme:` key in yaml config or similar env vars in the future. I'm also thinking about configurable colors in the yaml files in addition to pre-defined themes.

Unfortunately, there is a regression in this PR: colors in the list view are broken (maybe related to the nil pointer?). As seen from test output, the selected lines are no longer green. Will you be able to address this, or should I look for a fix myself?

And again, thank you for the contribution 😼

**Comment by orlangure** [comment]
@bashbunni, I suggested a fix to the regression in https://github.com/bashbunni/gocovsh/pull/1. If you have a better solution, feel free to close my PR 😼

**Comment by bashbunni** [comment]
Thanks so much for your help! I'll take another stab at resolving the error - I had a feeling it might be on the Bubble Tea side. I'll work on fixing that! Also happy to add the option to use a config file as well.

**Review by orlangure — APPROVED** [review]
This is so cool! Thank you.

There were some linter warnings, but I really wanted to merge this, so I just pushed my fixes directly, hope you don't mind.

**Pull request merged**
